version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt