# Use the faster container-based infrastructure
# https://docs.travis-ci.com/user/ci-environment/
sudo: false

language: python

services:
  - postgresql
  - mysql

addons:
  postgresql: "11"

matrix:
  include:
    #
    # Django 1.11
    - python: 2.7
      env: TOXENV=py27-dj111-sqlite
    - python: 3.5
      env: TOXENV=py35-dj111-sqlite
    - python: 3.6
      env: TOXENV=py36-dj111-sqlite

    - python: 2.7
      env: TOXENV=py27-dj111-postgres
    - python: 3.5
      env: TOXENV=py35-dj111-postgres
    - python: 3.6
      env: TOXENV=py36-dj111-postgres

    - python: 2.7
      env: TOXENV=py27-dj111-mysql
    - python: 3.5
      env: TOXENV=py35-dj111-mysql
    - python: 3.6
      env: TOXENV=py36-dj111-mysql

    #
    # Django 2.0
    - python: 3.5
      env: TOXENV=py35-dj20-sqlite
    - python: 3.6
      env: TOXENV=py36-dj20-sqlite
    - python: 3.7
      env: TOXENV=py37-dj20-sqlite

    - python: 3.5
      env: TOXENV=py35-dj20-postgres
    - python: 3.6
      env: TOXENV=py36-dj20-postgres
    - python: 3.7
      env: TOXENV=py37-dj20-postgres

    - python: 3.5
      env: TOXENV=py35-dj20-mysql
    - python: 3.6
      env: TOXENV=py36-dj20-mysql
    - python: 3.7
      env: TOXENV=py37-dj20-mysql

    #
    # Django 2.1
    - python: 3.5
      env: TOXENV=py35-dj21-sqlite
    - python: 3.6
      env: TOXENV=py36-dj21-sqlite
    - python: 3.7
      env: TOXENV=py37-dj21-sqlite

    - python: 3.5
      env: TOXENV=py35-dj21-postgres
    - python: 3.6
      env: TOXENV=py36-dj21-postgres
    - python: 3.7
      env: TOXENV=py37-dj21-postgres

    - python: 3.5
      env: TOXENV=py35-dj21-mysql
    - python: 3.6
      env: TOXENV=py36-dj21-mysql
    - python: 3.7
      env: TOXENV=py37-dj21-mysql

    #
    # Django 2.2
    - python: 3.5
      env: TOXENV=py35-dj22-sqlite
    - python: 3.6
      env: TOXENV=py36-dj22-sqlite
    - python: 3.7
      env: TOXENV=py37-dj22-sqlite

    - python: 3.5
      env: TOXENV=py35-dj22-postgres
    - python: 3.6
      env: TOXENV=py36-dj22-postgres
    - python: 3.7
      env: TOXENV=py37-dj22-postgres

    - python: 3.5
      env: TOXENV=py35-dj22-mysql
    - python: 3.6
      env: TOXENV=py36-dj22-mysql
    - python: 3.7
      env: TOXENV=py37-dj22-mysql

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

install:
  - pip install tox codecov

# Create MySQL and Postgres databases
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_ci_test;' -uroot

script: tox

# Can discuss again if somebody wants them.
notifications:
  email: false
